### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by dandv** [lourenzo/postgres-bluebird#4]
If so, how would it compare to the more current [pg-query-bluebird by @janpot](https://github.com/janpot/pg-query-bluebird)?

**Comment by lourenzo** [comment]
Actually, I just used this a few times, but it's still working on my installs. And yes, it's still maintained even since no further release is planned for this time.

It's quite simple, just a promisification using bluebird's `promisifyAll` method over some [pg](https://www.npmjs.com/package/pg) package's components such as `Client`, `Connection` and `Query`, and their prototypes.

This is the main difference to [pg-query-bluebird](https://github.com/janpot/pg-query-bluebird), which is built around [pq-query](https://www.npmjs.com/package/pg-query) package.

Regards,
Lourenzo
